/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffectationsRouteImport } from './routes/affectations'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as EquipementsRouteImport } from './routes/equipements'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ConducteursIndexRouteImport } from './routes/conducteurs.index'
import { Route as ConducteursDriverIdRouteImport } from './routes/conducteurs.$driverId'
import { Route as VehiculesIndexRouteImport } from './routes/vehicules.index'
import { Route as VehiculesVehicleIdRouteImport } from './routes/vehicules.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffectationsRoute = AffectationsRouteImport.update({
  id: '/affectations',
  path: '/affectations',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsRoute = EquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConducteursIndexRoute = ConducteursIndexRouteImport.update({
  id: '/conducteurs/',
  path: '/conducteurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConducteursDriverIdRoute = ConducteursDriverIdRouteImport.update({
  id: '/conducteurs/$driverId',
  path: '/conducteurs/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesIndexRoute = VehiculesIndexRouteImport.update({
  id: '/vehicules/',
  path: '/vehicules/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesVehicleIdRoute = VehiculesVehicleIdRouteImport.update({
  id: '/vehicules/$vehicleId',
  path: '/vehicules/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affectations': typeof AffectationsRoute
  '/agences': typeof AgencesRoute
  '/alertes': typeof AlertesRoute
  '/depenses': typeof DepensesRoute
  '/equipements': typeof EquipementsRoute
  '/locations': typeof LocationsRoute
  '/conducteurs/$driverId': typeof ConducteursDriverIdRoute
  '/vehicules/$vehicleId': typeof VehiculesVehicleIdRoute
  '/conducteurs/': typeof ConducteursIndexRoute
  '/vehicules/': typeof VehiculesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affectations': typeof AffectationsRoute
  '/agences': typeof AgencesRoute
  '/alertes': typeof AlertesRoute
  '/depenses': typeof DepensesRoute
  '/equipements': typeof EquipementsRoute
  '/locations': typeof LocationsRoute
  '/conducteurs/$driverId': typeof ConducteursDriverIdRoute
  '/vehicules/$vehicleId': typeof VehiculesVehicleIdRoute
  '/conducteurs': typeof ConducteursIndexRoute
  '/vehicules': typeof VehiculesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affectations': typeof AffectationsRoute
  '/agences': typeof AgencesRoute
  '/alertes': typeof AlertesRoute
  '/depenses': typeof DepensesRoute
  '/equipements': typeof EquipementsRoute
  '/locations': typeof LocationsRoute
  '/conducteurs/$driverId': typeof ConducteursDriverIdRoute
  '/vehicules/$vehicleId': typeof VehiculesVehicleIdRoute
  '/conducteurs/': typeof ConducteursIndexRoute
  '/vehicules/': typeof VehiculesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affectations'
    | '/agences'
    | '/alertes'
    | '/depenses'
    | '/equipements'
    | '/locations'
    | '/conducteurs/$driverId'
    | '/vehicules/$vehicleId'
    | '/conducteurs/'
    | '/vehicules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affectations'
    | '/agences'
    | '/alertes'
    | '/depenses'
    | '/equipements'
    | '/locations'
    | '/conducteurs/$driverId'
    | '/vehicules/$vehicleId'
    | '/conducteurs'
    | '/vehicules'
  id:
    | '__root__'
    | '/'
    | '/affectations'
    | '/agences'
    | '/alertes'
    | '/depenses'
    | '/equipements'
    | '/locations'
    | '/conducteurs/$driverId'
    | '/vehicules/$vehicleId'
    | '/conducteurs/'
    | '/vehicules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffectationsRoute: typeof AffectationsRoute
  AgencesRoute: typeof AgencesRoute
  AlertesRoute: typeof AlertesRoute
  DepensesRoute: typeof DepensesRoute
  EquipementsRoute: typeof EquipementsRoute
  LocationsRoute: typeof LocationsRoute
  ConducteursDriverIdRoute: typeof ConducteursDriverIdRoute
  VehiculesVehicleIdRoute: typeof VehiculesVehicleIdRoute
  ConducteursIndexRoute: typeof ConducteursIndexRoute
  VehiculesIndexRoute: typeof VehiculesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affectations': {
      id: '/affectations'
      path: '/affectations'
      fullPath: '/affectations'
      preLoaderRoute: typeof AffectationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements': {
      id: '/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof EquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conducteurs/': {
      id: '/conducteurs/'
      path: '/conducteurs'
      fullPath: '/conducteurs/'
      preLoaderRoute: typeof ConducteursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conducteurs/$driverId': {
      id: '/conducteurs/$driverId'
      path: '/conducteurs/$driverId'
      fullPath: '/conducteurs/$driverId'
      preLoaderRoute: typeof ConducteursDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/': {
      id: '/vehicules/'
      path: '/vehicules'
      fullPath: '/vehicules/'
      preLoaderRoute: typeof VehiculesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/$vehicleId': {
      id: '/vehicules/$vehicleId'
      path: '/vehicules/$vehicleId'
      fullPath: '/vehicules/$vehicleId'
      preLoaderRoute: typeof VehiculesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffectationsRoute: AffectationsRoute,
  AgencesRoute: AgencesRoute,
  AlertesRoute: AlertesRoute,
  DepensesRoute: DepensesRoute,
  EquipementsRoute: EquipementsRoute,
  LocationsRoute: LocationsRoute,
  ConducteursDriverIdRoute: ConducteursDriverIdRoute,
  VehiculesVehicleIdRoute: VehiculesVehicleIdRoute,
  ConducteursIndexRoute: ConducteursIndexRoute,
  VehiculesIndexRoute: VehiculesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
