/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiculesIndexRouteImport } from './routes/vehicules.index'
import { Route as VehiculesVehicleIdRouteImport } from './routes/vehicules.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesIndexRoute = VehiculesIndexRouteImport.update({
  id: '/vehicules/',
  path: '/vehicules/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesVehicleIdRoute = VehiculesVehicleIdRouteImport.update({
  id: '/vehicules/$vehicleId',
  path: '/vehicules/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vehicules/$vehicleId': typeof VehiculesVehicleIdRoute
  '/vehicules/': typeof VehiculesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vehicules/$vehicleId': typeof VehiculesVehicleIdRoute
  '/vehicules': typeof VehiculesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vehicules/$vehicleId': typeof VehiculesVehicleIdRoute
  '/vehicules/': typeof VehiculesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vehicules/$vehicleId' | '/vehicules/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vehicules/$vehicleId' | '/vehicules'
  id: '__root__' | '/' | '/vehicules/$vehicleId' | '/vehicules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VehiculesVehicleIdRoute: typeof VehiculesVehicleIdRoute
  VehiculesIndexRoute: typeof VehiculesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/': {
      id: '/vehicules/'
      path: '/vehicules'
      fullPath: '/vehicules/'
      preLoaderRoute: typeof VehiculesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/$vehicleId': {
      id: '/vehicules/$vehicleId'
      path: '/vehicules/$vehicleId'
      fullPath: '/vehicules/$vehicleId'
      preLoaderRoute: typeof VehiculesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VehiculesVehicleIdRoute: VehiculesVehicleIdRoute,
  VehiculesIndexRoute: VehiculesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
